n=input('Digite algo: ')
print('O tipo primitivo disso é: ',n)
print('Isso é um número? ',n.isnumeric())
print('Isso é uma letra? ',n.isalpha())
print('Isso é uma letra ou número ou ambos? ',n.isalnum())
print('Isso é um espaço em branco? ',n.isspace())
print('Isso é formado apenas por letras maiúsculas? ',n.isupper())
print('Isso é formado apenas por letras minúsculas? ',n.islower())
print('Isso está capitalizado? ',n.istitle())