nome = str(input('Escreva o seu nome completo: ')).strip()
print('Seu nome em maiúsculas é {}.'.format(nome.upper()))
print('Seu nome em minúsculas é {}.'.format(nome.lower()))
print('Esse nome tem {} letras.'.format(len(nome) - nome.count(' ')))
#print('Esse nome tem {} letras.'.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e tem {} letras.'.format(separa[0], len(separa[0])))